#!/bin/bash
#limpesa e configuração obdc

##clean files, not used 
echo "" > /etc/asterisk/func_odbc.conf
echo "" > /etc/asterisk/cdr_pgsql.conf
echo "" > /etc/asterisk/cdr_odbc.conf 
echo "" > /etc/asterisk/cdr_manager.con
echo "" > /etc/asterisk/cdr_custom.conf
echo "" > /etc/asterisk/cdr_beanstalkd.conf
echo "" > /etc/asterisk/cel_custom.conf
echo "" > /etc/asterisk/cel_pgsql.conf


apt update
apt install -y unixodbc odbcinst mariadb-client mariadb-server odbc-mariadb
systemctl enable mariadb
systemctl start mariadb

apt install python3-pip -y
apt install python3-xyzservices
apt install python3.11-venv
apt install python3-xyz

pip install alembic
pip install psycopg2-binary
pip install mysql-connector-python
apt install python3-pymysql/stable python3-mysqldb/stable -y
pip install mysqlclient
pip install "importlib_metadata==1.5.2"
pip install "zipp==1.2.0"
pip install "configparser==3.8.1"

#cd /usr/src/asterisk/contrib/ast-db-manage
#mv config.ini.sample config.ini

#MODIFICAR COM O USUARIO E SENHA DO BANCO
#nano /usr/src/asterisk/contrib/ast-db-manage/config.ini
#/usr/bin/mysql_secure_installation
#mysql -u root
#CREATE USER 'asterisk'@'localhost' IDENTIFIED BY '123456';
#CREATE DATABASE asterisk;
#GRANT ALL privileges on asterisk.* to 'asterisk'@'localhost' identified by '123456';
#FLUSH privileges;

#alembic -c config.ini upgrade head

#show databases;
#use asterisk;
#show tables;
